FROM python:3.8

WORKDIR /app

COPY iso-python/requirements.txt .

COPY iso-python/app.py .

RUN pip install --no-cache-dir -r requirements.txt

COPY iso-python ./iso-python

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

